# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-29 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('published_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('last_published_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('catagory', models.CharField(blank=True, max_length=200, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
            options={
                'ordering': ['-last_published_time'],
            },
        ),
    ]
